### ISSUE TITLE
MAM setting preference

### ISSUE THREAD

**Issue by tylorr** [otalk/jxt-xmpp#1]
I believe in this file: https://github.com/otalk/jxt-xmpp/blob/b46693adc13d164f3e54638c8af9239689e396cf/src/mam.js that lines 64 and 88 need to use `Utils.findOrCreate` instead of `Utils.find`. Otherwise, deeper in the callstack I get an error when calling find() on the container because it is an empty array the first time.

**Comment by legastero** [comment]
Good catch, thanks!
