### ISSUE TITLE
Extending core stanzas

### ISSUE THREAD

**Issue by sarumjanuch** [otalk/jxt-xmpp#12]
Hi Lance, i already wrote some custom IQ extensions with JXT, but i can't find out how to extend top level stanza fileds?
For example i want to add attributes to top level message among from to type etc, it it possible?

**Comment by legastero** [comment]
Here's an example: https://github.com/otalk/jxt-xmpp/blob/master/src/visibility.js#L8

**Comment by sarumjanuch** [comment]
Thanks a lot! This helped. Have a good day!
