### ISSUE TITLE
Pubsub create under wrong namespace

### ISSUE THREAD

**Issue by tylorr** [otalk/jxt-xmpp#2]
According to [XEP-0060](https://xmpp.org/extensions/xep-0060.html#owner-create) node creation should happen in the http://jabber.org/protocol/pubsub namespace not the http://jabber.org/protocol/pubsub#owner namespace

**Comment by legastero** [comment]
Agh, that's not confusing at all. Looks like there needs to also be a configure element in the pubsub namespace to go with the create.

Update to this and stanza.io on the way.

**Comment by tylorr** [comment]
Thank you
