### ISSUE TITLE
pubsub create instant node

### ISSUE THREAD

**Issue by tylorr** [otalk/jxt-xmpp#3]
Pubsub allows the creation of instant nodes where you do not provide a node attribute on the create tag as shown here: https://xmpp.org/extensions/xep-0060.html#example-130

It doesn't seem possible right now to create a stanza with a create tag that doesn't have a node attribute.

I'm not sure what needs to be changed to implement this but I noticed here https://github.com/otalk/jxt/blob/8c8ddf81c1ba91cb32fdecbfbf6d468b36682b3c/lib/helpers.js#L92-L96  that when setting a sub attribute the element is only created if the value evaluates to truthy.

Changing it to the following would fix this problem but I'm not sure how this would affect other parts of the code base.

```
sub = exports.createElement(NS, sub, xml.namespaceURI);
if (value) {
    sub.setAttribute(attr, value);
}
xml.appendChild(sub);
```

**Comment by tylorr** [comment]
Let me know if this was the right repo to post this to. Hard to figure out if I should post this to stanza.io, here, or jxt

**Comment by legastero** [comment]
This is the right repo for this issue :)

Until I can do more inspection to see if that change would cause other problems, I'll update this specific field to insert an empty `<create />` element if the value is the literal `true`.

**Comment by legastero** [comment]
Ok, that should work as expected now.
