### ISSUE TITLE
Report pubsub unsupported feature

### ISSUE THREAD

**Issue by tylorr** [otalk/jxt-xmpp#4]
When we get a feature-not-implemented error for pubsub would it be possible to report the feature attribute on the unsupported tag? Right now we only get a `pubsubCondition: unsupported` but it doesn't specify which feature.

**Comment by legastero** [comment]
There is now:

``` js
error: {
    condition: 'feature-not-implemented',
    pubsubCondition: 'unsupported',
    pubsubUnsupportedFeature: 'instant-nodes'
}
```
