### ISSUE TITLE
extendIQ is not defined.

### ISSUE THREAD

**Issue by xdumaine** [otalk/jxt-xmpp#8]
I'm not finding any reference to `extendIQ` on JXT, but this project is using it - was that something that was removed?

**Comment by legastero** [comment]
At the moment those are defined in the `jxt-xmpp-types` module, so you'd use this like so:

``` javascript
var JXT = require('jxt').createRegistry();
JXT.use(require('jxt-xmpp-types'));
JXT.use(require('jxt-xmpp'));
```

This split approach is rather silly in hindsight, but came from how I originally wanted to split all of the definitions into multiple modules (such as the `jingle-stanza` module you made).

**Comment by xdumaine** [comment]
Yeah, that's what I'm trying to update. I have that exactly and get the error...

**Comment by legastero** [comment]
Version difference, maybe? Latest is 3.0.

**Comment by xdumaine** [comment]
Zing.
